// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0f1wXbo9V8In8eBOZvfNO17JswiULJQ',
    appId: '1:483606864628:web:a0b5b0aa33d245c0f134a1',
    messagingSenderId: '483606864628',
    projectId: 'artgrade-882f7',
    authDomain: 'artgrade-882f7.firebaseapp.com',
    databaseURL: 'https://artgrade-882f7-default-rtdb.firebaseio.com',
    storageBucket: 'artgrade-882f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFM2HxZyHXvRobjmXGaL8x_ATdshA09yg',
    appId: '1:483606864628:android:3211adf7ed087b28f134a1',
    messagingSenderId: '483606864628',
    projectId: 'artgrade-882f7',
    databaseURL: 'https://artgrade-882f7-default-rtdb.firebaseio.com',
    storageBucket: 'artgrade-882f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK1dcdh8hMkmAHC2KEBFcU4GxCse_Lgrc',
    appId: '1:483606864628:ios:e5033806302bf11df134a1',
    messagingSenderId: '483606864628',
    projectId: 'artgrade-882f7',
    databaseURL: 'https://artgrade-882f7-default-rtdb.firebaseio.com',
    storageBucket: 'artgrade-882f7.firebasestorage.app',
    iosBundleId: 'com.dev.abhishek.artgrade.artgrade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK1dcdh8hMkmAHC2KEBFcU4GxCse_Lgrc',
    appId: '1:483606864628:ios:b0e6b04b2532bfdbf134a1',
    messagingSenderId: '483606864628',
    projectId: 'artgrade-882f7',
    databaseURL: 'https://artgrade-882f7-default-rtdb.firebaseio.com',
    storageBucket: 'artgrade-882f7.firebasestorage.app',
    iosBundleId: 'com.dev.abhishek.artgrade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg0f1wXbo9V8In8eBOZvfNO17JswiULJQ',
    appId: '1:483606864628:web:bbe703a2edd4d477f134a1',
    messagingSenderId: '483606864628',
    projectId: 'artgrade-882f7',
    authDomain: 'artgrade-882f7.firebaseapp.com',
    databaseURL: 'https://artgrade-882f7-default-rtdb.firebaseio.com',
    storageBucket: 'artgrade-882f7.firebasestorage.app',
  );
}
